# Generated by Django 5.0.3 on 2024-05-06 19:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('numero', models.IntegerField()),
                ('dirreccion', models.CharField(max_length=150)),
                ('departamento', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('local', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuairo.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField()),
                ('pago', models.BooleanField(default=False)),
                ('fecha_de_entrega', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nombre', models.CharField(default='factura #', max_length=60)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuairo.cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zapato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Calzado_deportivo', 'calzado deportivo'), ('botas', 'Botas'), ('sandalias', 'Sandalias'), ('Calzado para niño', 'calzado para niño'), ('Calzado para niña', 'calzado para niña'), ('Calzado formal', 'calzado formal'), ('Calazado para hombre', 'calzado para hombre'), ('Calazado para mujer', 'calzado para mujer'), ('Calazado unisex', 'calzado unisex')], max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('terminado', 'Terminado'), ('en proceso', 'en Proceso'), ('no iniciado', 'No iniciado')], default='no iniciado', max_length=50)),
                ('canitdad', models.IntegerField(default=0)),
                ('talla', models.IntegerField(default=0)),
                ('valor', models.IntegerField(default=0)),
                ('fecha_pedido', models.DateField(default=django.utils.timezone.now)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='usuairo.factura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zapato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuairo.zapato')),
            ],
        ),
    ]
