# Generated by Django 5.0.3 on 2024-05-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuairo', '0004_encuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='pregunta_6',
            field=models.TextField(default='recomendaciones:'),
        ),
    ]
