# Generated by Django 5.0.3 on 2024-05-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuairo', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nombre_empresa',
            field=models.CharField(default='nombre', max_length=100),
        ),
    ]
